version: '3.4'

services:
  fuzzylogic.mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  fuzzylogic.portal:
    image: ${DOCKER_REGISTRY-}fuzzylogicportal
    build:
      context: .
      dockerfile: FuzzyLogic.Portal/Dockerfile
    links:
      - fuzzylogic.mongo